FROM postgres:18-alpine

# RUN mkdir -p /var/lib/postgresql/data && chown -R postgres:postgres /var/lib/postgresql/data
# RUN mkdir -p /var/lib/postgresql/18/docker && chown -R postgres:postgres /var/lib/postgresql/18/docker