services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transcendence-frontend
    image: frontend:v1
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
    networks:
      - transcendence_network
    restart: unless-stopped



networks:
  transcendence_network:
    driver: bridge