---
config:
  layout: dagre
  look: neo
---
flowchart LR
 subgraph SERVICES["MICROSERVICES"]
        AUTH["AUTH<br>
        <b>• OAuth 2.0</b>
        <b>• JWT generation</b>
        <b>• 2FA</b>
        <b>• Token validation</b>
        <b>• Password reset</b>
        <b>• Rate limiting</b>"]
        PLAYER["PLAYER<br>
        <b>• CRUD profiles</b>
        <b>• Avatar upload</b>
        <b>• Friends system</b>
        <b>• Statistics</b>
        <b>• Game history</b>
        <b>• Achievements</b>"]
        LOBBY["LOBBY<br>
        <b>• Rooms CRUD</b>
        <b>• Join/Leave</b>
        <b>• Matchmaking</b>
        <b>• Room config</b>
        <b>• Ready check</b>
        <b>• Start game</b>"]
        GAME["GAME + WEBSOCKETS<br>
        <b>• State machine</b>
        <b>• Roles attribution</b>
        <b>• Votes processing</b>
        <b>• Phase management</b>
        <b>• Win conditions</b>
        <b>• WebSocket server</b>
        <b>• Chat in-game</b>
        <b>• Broadcast events</b>"]
  end
    CLIENTS["CLIENTS<br><br>React SPA + Mobile PWA<br><br><b>Interface utilisateur</b>"] ==> GATEWAY["API GATEWAY (Nginx)<br><br><b>ROUTES :</b><br>/api/lobby/ <br>/api/auth/ <br>/api/player/ <br>/api/game/ <br>/api/chat/ <br>/ws/"]
    GATEWAY ==> SERVICES
    SERVICES ==> PG["PostgreSQL<br><br>
    <b>4 services = 4 schemas</b><br>
    • <b>auth_db</b> : users, oauth_tokens, sessions, refresh_tokens<br>
    • <b>player_db</b> : profiles, friendships, statistics, achievements<br>
    • <b>lobby_db</b> : rooms, room_players, room_configs, invitations<br>
    • <b>game_db</b> : games, game_players, game_events, game_phases, votes, messages<br>"] & REDIS["Redis (Cache + Pub/Sub)<br><br>
    <b>Namespaces:</b><br>
    • Auth: session, ratelimit, 2FA
    • Player: profile, presence, friends:online
    • Lobby: room:players, matchmaking, room:config
    • Game: state, votes, ws:connections, chat:messages<br><br>
    <b>Pub/Sub channels:</b><br>
    • game:events/chat, lobby:updates, global:presence"]
    LOBBY -. POST /internal/game/create (room_id, players, config).-> GAME

    PG@{ shape: cyl}
    REDIS@{ shape: cyl}
     AUTH:::serviceStyle
     PLAYER:::serviceStyle
     LOBBY:::serviceStyle
     GAME:::serviceStyle
     CLIENTS:::clientStyle
     GATEWAY:::gatewayStyle
     PG:::dbStyle
     REDIS:::redisStyle
    classDef clientStyle fill:#e1f5ff,stroke:#01579b,stroke-width:3px,color:#000
    classDef gatewayStyle fill:#fff3e0,stroke:#e65100,stroke-width:3px,color:#000
    classDef serviceStyle fill:#f3e5f5,stroke:#4a148c,stroke-width:2px,color:#000
    classDef dbStyle fill:#ffebee,stroke:#b71c1c,stroke-width:2px,color:#000
    classDef redisStyle fill:#fff9c4,stroke:#f57f17,stroke-width:2px,color:#000